#! /usr/bin/env bash

if [[ -f "$(pwd)/$1" ]]; then
  site="$(pwd)/$1"
elif [[ "$1" == "http"* ]]; then
  site="$1"
elif [[ "$1" == "file"* ]]; then
  site="$1"
else
  site="http://$1"
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  open -a "Google Chrome" $site
else
  /mnt/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe $site
fi

