#! /usr/bin/env bash

NOME_SIM=$1
echo Elaboro ${NOME_SIM}
ls -l ${NOME_SIM} > ${NOME_SIM}_on_disk.txt
cart_dir ${NOME_SIM} > ${NOME_SIM}_on_tape.txt
awk '{ print $9 " " $5 }' ${NOME_SIM}_on_disk.txt > ${NOME_SIM}_on_disk_clean.txt
awk '{ print $1 " " $2 }' ${NOME_SIM}_on_tape.txt > ${NOME_SIM}_on_tape_clean.txt
cat ${NOME_SIM}_on_disk_clean.txt | sort > ${NOME_SIM}_on_disk_sort.txt
cat ${NOME_SIM}_on_tape_clean.txt | sort > ${NOME_SIM}_on_tape_sort.txt
cat ${NOME_SIM}_on_tape_sort.txt ${NOME_SIM}_on_disk_sort.txt > ${NOME_SIM}_sort.txt
cat ${NOME_SIM}_sort.txt | sort > ${NOME_SIM}_sort2.txt
mv ${NOME_SIM}_sort2.txt ${NOME_SIM}_sort.txt
cat ${NOME_SIM}_sort.txt | uniq -c > log.txt
cat log.txt | sort > log2.txt
mv log2.txt log.txt
mv log.txt ${NOME_SIM}_diff.txt
echo 'Fatto!'
