#! /bin/bash

echo "Tot:       "`llq |tail -1`
echo "Debug:     "`llq -c debug |tail -1`
echo "LongDebug: "`llq -c longdebug |tail -1`
echo "Parallel:  "`llq -c parallel |tail -1`
echo "SmallPar:  "`llq -c smallpar |tail -1`
echo "BigPar:    "`llq -c bigpar |tail -1`
echo "Serial:    "`llq -c serial | tail -1`
